# Generated by Django 6.0.7 on 2026-07-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
