# Generated by Django 6.0.7 on 2026-07-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_submission_feedback_submission_graded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
