# Generated by Django 6.0.7 on 2026-08-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_alter_submission_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('course', 'student', 'date')},
        ),
    ]
